// <auto-generated />
namespace PornSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedmain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmain));
        
        string IMigrationMetadata.Id
        {
            get { return "201804201243557_addedmain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
