//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PornSite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PornSite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Came here to beat some meat? This page is for adults only! Proceed only if you are 18+..
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All videos.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anal.
        /// </summary>
        public static string Anal {
            get {
                return ResourceManager.GetString("Anal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wana get to porn quickly? Get our app!.
        /// </summary>
        public static string App1 {
            get {
                return ResourceManager.GetString("App1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app will appear as Excel in your phone..
        /// </summary>
        public static string App2 {
            get {
                return ResourceManager.GetString("App2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO BACK TO THE PAGE.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories_modal {
            get {
                return ResourceManager.GetString("Categories_modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos from category.
        /// </summary>
        public static string Categories_page {
            get {
                return ResourceManager.GetString("Categories_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIES.
        /// </summary>
        public static string Category_header {
            get {
                return ResourceManager.GetString("Category_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can play the video preview by holding your finger on the video thumbnail or title (works on Chrome only).
        /// </summary>
        public static string Chrome {
            get {
                return ResourceManager.GetString("Chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website uses cookies. By using it you agree with the way we use them to improve your experience..
        /// </summary>
        public static string Cookies {
            get {
                return ResourceManager.GetString("Cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string Czech {
            get {
                return ResourceManager.GetString("Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one will catch you watching porn now!.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you don&apos;t need to worry about getting caught watching porn. Simply press any key on your keyboard anywhere on the page and it will disappear! Go ahead, try it!.
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to us on facebook.
        /// </summary>
        public static string Fb {
            get {
                return ResourceManager.GetString("Fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For firefox users:.
        /// </summary>
        public static string Firefox1 {
            get {
                return ResourceManager.GetString("Firefox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order fort the &quot;safety button&quot; to work with keyboard, you need to switch to different browser, etc. Google Chrome..
        /// </summary>
        public static string Firefox2 {
            get {
                return ResourceManager.GetString("Firefox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what does it do?.
        /// </summary>
        public static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILF.
        /// </summary>
        public static string MILF {
            get {
                return ResourceManager.GetString("MILF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show only videos for phones.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, fuck off!.
        /// </summary>
        public static string Nope {
            get {
                return ResourceManager.GetString("Nope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure!.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key!.
        /// </summary>
        public static string Press {
            get {
                return ResourceManager.GetString("Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended videos.
        /// </summary>
        public static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIFE NEARBY!.
        /// </summary>
        public static string Safety_button {
            get {
                return ResourceManager.GetString("Safety_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching:.
        /// </summary>
        public static string SearchParam {
            get {
                return ResourceManager.GetString("SearchParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recommended videos.
        /// </summary>
        public static string Similiar {
            get {
                return ResourceManager.GetString("Similiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended videos.
        /// </summary>
        public static string Similiar_header {
            get {
                return ResourceManager.GetString("Similiar_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch porn safely! - Vymasti.si.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODAY.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to most viewed.
        /// </summary>
        public static string Viewed {
            get {
                return ResourceManager.GetString("Viewed", resourceCulture);
            }
        }
    }
}
